import type { Person } from "@/lib/types";

export const seedPeople: Person[] = [
  { id: 1, name: "Aquino, Carlos Gabriel L. (Legaspi)", email: "kuhyewlosgabriel@gmail.com", birthdate: "2001-05-29", created_at: "", updated_at: "" },
  { id: 2, name: "Domequil, Kyle A. (Alvez)", email: "alvezdomequil@gmail.com", birthdate: "2001-09-12", created_at: "", updated_at: "" },
  { id: 3, name: "Espina, Francis", email: "francisespina2121@gmail.com", birthdate: "2001-09-21", created_at: "", updated_at: "" },
  { id: 4, name: "Antido, Rhea Eladia Mae A. (Arias)", email: "rem.antido@gmail.com", birthdate: "2001-09-30", created_at: "", updated_at: "" },
  { id: 5, name: "Sequito, Joshua Karl", email: "daca.joshua@gmail.com", birthdate: "2001-10-04", created_at: "", updated_at: "" },
  { id: 6, name: "Caalim, Hannah Janinne G. (Garcia)", email: "hannahjaninne@gmail.com", birthdate: "2001-10-18", created_at: "", updated_at: "" },
  { id: 7, name: "Estillore, Azelie Judd N. (Nueve)", email: "ajnestillore@gmail.com", birthdate: "2001-10-28", created_at: "", updated_at: "" },
  { id: 8, name: "Gerpacio, Marie Claire", email: "gerpaciomarieclaire@gmail.com", birthdate: "2001-11-08", created_at: "", updated_at: "" },
  { id: 9, name: "Piczon, Winston Emilio M.", email: "memelpiczon@gmail.com", birthdate: "2001-11-29", created_at: "", updated_at: "" },
  { id: 10, name: "Merino, John Lester Czar C. (Corocoto)", email: "johnlestermerino@gmail.com", birthdate: "2002-01-01", created_at: "", updated_at: "" },
  { id: 11, name: "Yepez, April Joy R. (Redubla)", email: "apriljoyyepez@gmail.com", birthdate: "2002-01-18", created_at: "", updated_at: "" },
  { id: 12, name: "Labrague, Maxinne C. (Castor)", email: "maxinnelabrague@gmail.com", birthdate: "2002-02-03", created_at: "", updated_at: "" },
  { id: 13, name: "Sacedor, Loyd Albert V. (Vaporoso)", email: "loydalberts@gmail.com", birthdate: "2002-02-23", created_at: "", updated_at: "" },
  { id: 14, name: "Gabiana, Melben Kian R. (Rama)", email: "gabianakian06@gmail.com", birthdate: "2002-03-14", created_at: "", updated_at: "" },
  { id: 15, name: "Cada, Shiela N. (Nebril)", email: "theshielacada@gmail.com", birthdate: "2002-03-28", created_at: "", updated_at: "" },
  { id: 16, name: "Zabala, Mary Rose V. (Villamor)", email: "maryrosezabala329@gmail.com", birthdate: "2002-03-29", created_at: "", updated_at: "" },
  { id: 17, name: "Globio, Diana Rose D. (Ditalo)", email: "dianaroseglobio@gmail.com", birthdate: "2002-04-15", created_at: "", updated_at: "" },
  { id: 18, name: "Nerida, Ma. Arabella Jen A. (Antillon)", email: "arabellajennerida22@gmail.com", birthdate: "2002-04-22", created_at: "", updated_at: "" },
  { id: 19, name: "Lozada, Ma. Wella T. (Tapayan)", email: "wellalzd@gmail.com", birthdate: "2002-04-23", created_at: "", updated_at: "" },
  { id: 20, name: "Po, Nikhaella Faye", email: "nikhaellahoran@gmail.com", birthdate: "2002-05-04", created_at: "", updated_at: "" },
  { id: 21, name: "Morante, Angel May A. (Alejandro)", email: "up.angelmaymorante.1@gmail.com", birthdate: "2002-05-30", created_at: "", updated_at: "" },
  { id: 22, name: "Dano, Julianne P. (Panal)", email: "danojulianne@gmail.com", birthdate: "2002-06-02", created_at: "", updated_at: "" },
  { id: 23, name: "Blando, Jullianne Marie B. (Balase)", email: "julliannebalase@gmail.com", birthdate: "2002-06-13", created_at: "", updated_at: "" },
  { id: 24, name: "Permejo, John Lester G. (Gallamos)", email: "johnlesterpermejo@gmail.com", birthdate: "2002-07-19", created_at: "", updated_at: "" },
  { id: 25, name: "Luceres, Vall James P. (Paghubasan)", email: "james.luceres@gmail.com", birthdate: "2002-07-24", created_at: "", updated_at: "" },
  { id: 26, name: "Voces, Merielle Angeli R. (Rafales)", email: "meryeeelvoces@gmail.com", birthdate: "2002-08-02", created_at: "", updated_at: "" },
  { id: 27, name: "Alicaba, Khristina O. (Oracion)", email: "patindangalicaba@gmail.com", birthdate: "2002-08-08", created_at: "", updated_at: "" },
  { id: 28, name: "Daria, Charlene Jean A. (Agarro)", email: "charlenejeandaria@gmail.com", birthdate: "2002-09-09", created_at: "", updated_at: "" },
  { id: 29, name: "Yu, Mar Yoneh Antoinette N. (Nalda)", email: "yaniyaniyu21@gmail.com", birthdate: "2002-09-21", created_at: "", updated_at: "" },
  { id: 30, name: "Darang, Dan Harlquin C. (Caprecho)", email: "dcdarang@gmail.com", birthdate: "2002-09-29", created_at: "", updated_at: "" },
  { id: 31, name: "Marquez, Khryzha Mae Joy M. (Maranon)", email: "kmjmarquez@gmail.com", birthdate: "2002-11-03", created_at: "", updated_at: "" },
  { id: 32, name: "Abendan, Jamaica R. (Rodriguez)", email: "rabendan.jamaica@gmail.com", birthdate: "2002-11-14", created_at: "", updated_at: "" },
  { id: 33, name: "Centino, Camille Rose P. (Pedere)", email: "camille.r.centino@gmail.com", birthdate: "2002-11-19", created_at: "", updated_at: "" },
  { id: 34, name: "Tan, Jay Samuel E. (Espelimbergo)", email: "jaysamuelt@gmail.com", birthdate: "2003-01-16", created_at: "", updated_at: "" },
  { id: 35, name: "Chu, Kim Trisha G. (Go)", email: "ktgochu@gmail.com", birthdate: "2003-02-01", created_at: "", updated_at: "" },
  { id: 36, name: "Sevilla, Ma. Angela G. (Gomez)", email: "jellasevilla.27@gmail.com", birthdate: "2003-03-27", created_at: "", updated_at: "" },
  { id: 37, name: "Bardelas, Vynnex P. (Pineda)", email: "vynbardelas@gmail.com", birthdate: "2003-06-05", created_at: "", updated_at: "" },
  { id: 38, name: "Morata, Keisha F. (Fernandez)", email: "keishafernandezmorata@gmail.com", birthdate: "2003-06-13", created_at: "", updated_at: "" },
  { id: 39, name: "Piangco, Mark Lester M. (Madilangan)", email: "piangcomarklester7@gmail.com", birthdate: "2003-06-21", created_at: "", updated_at: "" },
  { id: 40, name: "Rodriguez, Lexa Marie V. (Villanueva)", email: "lexamarievr@gmail.com", birthdate: "2003-07-04", created_at: "", updated_at: "" },
  { id: 41, name: "Guda, Mark John C. (Catapal)", email: "gudamarkjohn@gmail.com", birthdate: "2003-07-20", created_at: "", updated_at: "" },
  { id: 42, name: "Cabagio, Jonah Mae L. (Laurente)", email: "cabagiojonahmae03@gmail.com", birthdate: "2003-07-25", created_at: "", updated_at: "" },
  { id: 43, name: "Molina, Princess Eldhy E.(Engracial)", email: "eldhymolina.princess@gmail.com", birthdate: "2003-08-23", created_at: "", updated_at: "" },
  { id: 44, name: "Lachica, Paul", email: "Paullachica13@gmail.com", birthdate: "2004-02-24", created_at: "", updated_at: "" },
];
